"""empty message

Revision ID: 0b85402b04ea
Revises: 
Create Date: 2024-12-11 21:18:11.085946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b85402b04ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Usuwanie tabeli 'items'
    op.drop_table('items')

    # Zmiany w tabeli 'datadepot_db'
    with op.batch_alter_table('datadepot_db', schema=None) as batch_op:
        # Dodawanie nowej kolumny 'postalZip'
        batch_op.add_column(sa.Column('postalZip', sa.String(length=10), nullable=True))

        # Zmiana typu kolumny 'list' na JSON
        op.execute('ALTER TABLE datadepot_db ALTER COLUMN list TYPE JSON USING list::json')

        # Usuwanie kolumny 'postalzip'
        batch_op.drop_column('postalzip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datadepot_db', schema=None) as batch_op:
        # Dodawanie kolumny 'postalzip'
        batch_op.add_column(sa.Column('postalzip', sa.VARCHAR(length=10), autoincrement=False, nullable=True))

        # Zmiana typu kolumny 'list' z JSON na VARCHAR
        op.execute('ALTER TABLE datadepot_db ALTER COLUMN list TYPE VARCHAR USING list::text')

        # Usuwanie kolumny 'postalZip'
        batch_op.drop_column('postalZip')

    # Tworzenie tabeli 'items'
    op.create_table('items',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    # ### end Alembic commands ###
